### ISSUE TITLE
List redraws get corrupted.

### ISSUE THREAD

**Issue by TBurchfield** [TBurchfield/cursello#1]
I tried doing with this with a `stdscr.clear()` at the top of the `refresh_lists` function, but this prevents some other things from being printed.

There's probably a better way of refactoring this functionality.

demo: https://asciinema.org/a/5KLOxND6HtJbGULdITr2QSVP6

**Comment by dsmith47** [comment]
Is the only issue on this PR the awkward redraw inside of the bounding box? Or are we trying to optimize list draws together?

**Comment by TBurchfield** [comment]
A better approach to draws would be the end goal.

**Comment by dsmith47** [comment]
Issue seems to be a symptom of Curses drawing new artifacts each time without clearing old items. To ensure items are capable of shifting both horizontally and vertically, entire screen may need to be cleared.

Happy to take a crack at this if no one else is.

**Comment by TBurchfield** [comment]
It seems no one else has looked at it.  Crack away. :+1: :smile:

**Comment by dsmith47** [comment]
New approach and updated I/O suggest in this PR #6
