### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by TBurchfield** [TBurchfield/cursello#2]
Cursello needs to have persistence.  This largely involves

- Some sort of write command to write out the state to some sort of file.  I would prefer to use [pickle](https://docs.python.org/2/library/pickle.html), unless you have a different suggestion.
- Some sort of "Are you sure you want to quit without saving?" prompt if the state has changed it was last written out.
- Most importantly, loading this information on start.

**Comment by TBurchfield** [comment]
Upon consideration, something like [yaml](http://yaml.org/) might work better, so that it's human readable.

**Comment by dsmith47** [comment]
YAML is the easiest to parse on the command line with shell tools as well.

**Comment by dsmith47** [comment]
I'd propose a YAML module that stores a dictionary mapping List Names to lists of items (similar to how the runtime stores things) and checking for file at startup before using a default configuration (from a defaults file) and adding a trap to dump current state of cursello board on exit.

I would start storing list files in  `~/.cursello/`

Can start on this now if no one else wants it.

**Comment by TBurchfield** [comment]
Resolved by @dsmith47 's 91a4792f21fe3796359b844732b52b9674ddc3b5
